
'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Toaster } from 'react-hot-toast'
import { createContext, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
export  const RecoveryContext=createContext();
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  const[page,setPage]=useState("login")
  const[email,setEmail]=useState()
  const[otp,setOTP]=useState();
  return (

    <RecoveryContext.Provider value={{page,setPage,otp,setOTP,setEmail,email}}>
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Toaster/>
    </html>


    </RecoveryContext.Provider>

  )
}
